
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 4702', 'Durable keyboard with advanced features', 8820.16, 38);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 2323', 'Compact laptop with sleek features', 5850.06, 109);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 6646', 'Modern camera with sleek features', 8711.34, 73);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 4799', 'Wireless laptop with compact features', 2822.7, 17);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 5059', 'Lightweight camera with modern features', 10753.43, 161);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 8249', 'Wireless phone with advanced features', 7501.16, 66);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 5301', 'Advanced mouse with eco-friendly features', 370.35, 72);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 2751', 'Modern desk with smart features', 13329.47, 110);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 7855', 'High Quality monitor with smart features', 6099.37, 33);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 1929', 'Sleek phone with high quality features', 13515.2, 194);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 4876', 'Durable laptop with lightweight features', 11875.3, 57);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 3758', 'Wireless monitor with eco-friendly features', 2498.69, 151);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 7409', 'Sleek desk with modern features', 3985.82, 37);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 9415', 'Durable keyboard with lightweight features', 11549.73, 84);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 4200', 'Compact desk with advanced features', 4694.23, 112);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 5275', 'High Quality desk with smart features', 11362.67, 98);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 6849', 'Durable laptop with sleek features', 10217.44, 115);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 3924', 'Compact mouse with smart features', 7965.44, 30);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 4592', 'High Quality desk with sleek features', 11303.25, 100);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 9049', 'High Quality keyboard with wireless features', 3689.97, 14);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 3649', 'Smart camera with advanced features', 6232.04, 126);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 3648', 'Compact camera with smart features', 8178.11, 123);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 3198', 'Durable phone with lightweight features', 1010.96, 31);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 1619', 'Sleek keyboard with lightweight features', 7099.9, 116);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 9118', 'Smart camera with modern features', 4899.61, 199);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 9391', 'Eco-Friendly tablet with eco-friendly features', 3920.02, 127);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 7703', 'Smart speaker with sleek features', 14519.66, 44);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 6568', 'Durable chair with smart features', 416.64, 127);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 4122', 'Eco-Friendly speaker with wireless features', 10680.89, 39);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 9126', 'Compact camera with wireless features', 11566.36, 101);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 8976', 'Durable desk with high quality features', 11270.62, 85);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 4957', 'Lightweight tablet with compact features', 14623.02, 18);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 1836', 'Modern desk with sleek features', 2914.54, 190);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 9714', 'Smart desk with high quality features', 1501.24, 46);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 5151', 'Advanced camera with high quality features', 3198.2, 127);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 3295', 'Modern tablet with advanced features', 494.61, 162);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 2165', 'Sleek keyboard with wireless features', 7865.7, 18);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 4483', 'Sleek camera with lightweight features', 8323.53, 197);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 8537', 'High Quality desk with smart features', 3153.32, 141);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 6034', 'Modern laptop with modern features', 2716.43, 97);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 7501', 'Compact speaker with lightweight features', 5277.18, 197);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 9430', 'Advanced mouse with eco-friendly features', 3389.28, 187);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 8758', 'Eco-Friendly tablet with compact features', 9567.08, 57);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 6716', 'Sleek laptop with durable features', 14294.61, 179);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 6342', 'Eco-Friendly keyboard with high quality features', 12967.86, 17);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 4320', 'Smart mouse with lightweight features', 11958.21, 148);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 9103', 'Durable camera with high quality features', 738.26, 111);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 8299', 'Sleek desk with advanced features', 10111.47, 35);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 8574', 'Lightweight chair with compact features', 2956.76, 10);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 3000', 'Sleek chair with high quality features', 10551.09, 105);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 1628', 'Compact monitor with wireless features', 9520.85, 100);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 7807', 'Modern desk with smart features', 4890.01, 43);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 7121', 'High Quality keyboard with eco-friendly features', 4379.51, 196);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 5672', 'High Quality keyboard with modern features', 13911.05, 49);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 6434', 'Durable phone with high quality features', 12486.2, 93);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 5152', 'High Quality keyboard with lightweight features', 7179.53, 46);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 8143', 'Durable laptop with wireless features', 1695.79, 92);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 2510', 'Eco-Friendly chair with smart features', 6894.06, 121);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 2423', 'Advanced desk with modern features', 11268.71, 197);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 4266', 'Durable phone with high quality features', 8327.7, 52);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 9583', 'Eco-Friendly laptop with wireless features', 9171.67, 73);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 9154', 'Compact camera with smart features', 12788.03, 47);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 6080', 'High Quality chair with modern features', 7538.03, 182);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 5236', 'Advanced phone with lightweight features', 11052.36, 101);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 2761', 'Advanced desk with smart features', 1580.87, 48);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 2368', 'Sleek desk with advanced features', 8415.68, 114);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 4657', 'Durable speaker with modern features', 1674.12, 134);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 1687', 'Sleek desk with lightweight features', 5993.05, 129);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 3813', 'Sleek desk with high quality features', 13675.82, 100);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 8944', 'High Quality laptop with wireless features', 9046.69, 160);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 2737', 'Compact tablet with modern features', 1084.39, 133);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 2626', 'Eco-Friendly keyboard with compact features', 13886.32, 12);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 9160', 'Wireless tablet with modern features', 5559.54, 132);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 4797', 'Advanced desk with sleek features', 11402.26, 41);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 5301', 'Modern phone with smart features', 1214.81, 168);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 8876', 'Smart camera with wireless features', 13023.98, 33);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 4646', 'Wireless mouse with modern features', 7617.6, 163);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 8313', 'Advanced speaker with durable features', 5839.63, 142);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Camera 6356', 'Modern camera with high quality features', 781.3, 139);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 4880', 'Advanced desk with advanced features', 5249.41, 168);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 2507', 'Modern tablet with smart features', 11799.85, 124);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 7337', 'Durable mouse with sleek features', 9117.19, 60);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 9344', 'Wireless monitor with eco-friendly features', 10889.31, 30);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 8703', 'Durable monitor with wireless features', 10640.52, 131);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 9946', 'Smart chair with compact features', 6579.13, 161);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 5135', 'Advanced mouse with lightweight features', 10316.32, 82);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 2150', 'Durable chair with smart features', 13404.0, 59);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 6721', 'Durable desk with modern features', 359.04, 31);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 6518', 'Compact laptop with eco-friendly features', 8943.23, 31);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 3397', 'Compact laptop with compact features', 11256.66, 192);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Mouse 2795', 'Lightweight mouse with wireless features', 2770.1, 190);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Phone 6713', 'Smart phone with smart features', 1039.98, 198);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Keyboard 4315', 'Lightweight keyboard with smart features', 10291.89, 104);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Chair 7039', 'Modern chair with eco-friendly features', 1636.41, 25);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Laptop 4251', 'Lightweight laptop with advanced features', 9362.87, 170);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 6045', 'Advanced desk with sleek features', 5812.73, 13);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Desk 8330', 'Advanced desk with durable features', 5488.73, 195);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Monitor 5387', 'Wireless monitor with compact features', 8830.28, 92);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Speaker 1646', 'Advanced speaker with eco-friendly features', 7199.95, 38);
INSERT INTO products (name, description, price, stock_quantity) VALUES ('Tablet 4788', 'Sleek tablet with wireless features', 1343.06, 75);